export const FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS_REQUEST';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILURE';

export const FETCH_PROJECT_REQUEST = 'FETCH_PROJECT_REQUEST';
export const FETCH_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS';
export const FETCH_PROJECT_FAILURE = 'FETCH_PROJECT_FAILURE';

export const DELETE_PROJECT_REQUEST = 'FETCH_PROJECT_REQUEST';
export const DELETE_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAILURE = 'FETCH_PROJECT_FAILURE';
